export const ACTION_TYPES = {
  // ui
  SET_CURRENT_TAB: 'SET_CURRENT_TAB',
  SET_FILTER_BAR_VISIBLE: 'SET_FILTER_BAR_VISIBLE',
  SET_SELECTED_CHART: 'SET_SELECTED_CHART',
  SET_SELECTED_CHART_BY_ID: 'SET_SELECTED_CHART_BY_ID',
  SET_SORT_ORDER: 'SET_SORT_ORDER',

  // db status
  SET_DB_STATUS: 'SET_DB_STATUS',

  // cached db entries in state
  SET_TASK_SUMMARIES: 'SET_TASK_SUMMARIES',
  SET_SKILLS: 'SET_SKILLS',
  SET_USERS: 'SET_USERS',
  SET_TAGS: 'SET_TAGS',

  // current user
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  UPDATE_CURRENT_USER: 'UPDATE_CURRENT_USER',

  // filters
  INIT_FILTERS: 'INIT_FILTERS',
  INIT_FILTER_PARAMS: 'INIT_FILTER_PARAMS',
  RESET_FILTER_PARAMS: 'RESET_FILTER_PARAMS',
  RESET_ALL_FILTER_PARAMS: 'RESET_ALL_FILTER_PARAMS',
  SET_FILTER_PARAMS: 'SET_FILTER_PARAMS',
  SET_FILTERS_PARAMS: 'SET_FILTERS_PARAMS',
};
