export const ACTION_TYPES = {
  SET_TASKS: 'SET_TASKS',
  SET_USERS: 'SET_USERS',
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  SET_SKILLS: 'SET_SKILLS',
  SET_DATE_RANGE: 'SET_DATE_RANGE',
  SET_VACANCIES: 'SET_VACANCIES',
  SET_INTEREST: 'SET_INTEREST',
  SET_CONTRIBUTION_LINKS: 'SET_CONTRIBUTION_LINKS',

  SET_FILTERS: 'SET_FILTERS',
  RESET_FILTER: 'RESET_FILTER',
  RESET_FILTERS: 'RESET_FILTERS',
  SET_FILTER_PARAMS: 'SET_FILTER_PARAMS',
  SET_FILTERS_PARAMS: 'SET_FILTERS_PARAMS',

  SET_CURRENT_TAB: 'SET_CURRENT_TAB',
  SET_CURRENT_TAB_BY_ID: 'SET_CURRENT_TAB_BY_ID',

  SET_FILTER_BAR_VISIBLE: 'SET_FILTER_BAR_VISIBLE',

  SET_SELECTED_CHART: 'SET_SELECTED_CHART',
  SET_SELECTED_CHART_BY_ID: 'SET_SELECTED_CHART_BY_ID',

  SET_SORT_ORDER: 'SET_SORT_ORDER',

  SET_DB_STATUS: 'SET_DB_STATUS',
};
