export const FIND_TASKS = 'FIND TASKS';
export const ADD_TASK = 'ADD TASK';
export const REMOVE_TASK = 'REMOVE TASK';
export const SET_TASKS_LOADED = 'SET_TASKS_LOADED';

export const ADD_TASK_FILTER = 'ADD TASK FILTER';
export const REMOVE_TASK_FILTER = 'REMOVE TASK FILTER';
export const CLEAR_FILTERS = 'CLEAR_FILTERS';
