export const TASK_LIST_FILTER_CONTROL_IDS = {
  CREATED_DATE: 'CREATED_DATE',
  CREATED_BY: 'CREATED_BY',
  RUNNING: 'RUNNING',
  START_DATE: 'START_DATE',
  END_DATE: 'END_DATE',
  VACANCIES: 'VACANCIES',
  TYPE: 'TYPE',
  SEARCH_FIELD: 'SEARCH_FIELD',
};
