// tasks
export const SET_TASKS = 'SET_TASKS';

// task list filters
export const SET_TASK_LIST_FILTER_CONTROL = 'SET_TASK_LIST_FILTER_CONTROL';
export const SET_TASK_LIST_FILTER_CONTROLS = 'SET_TASK_LIST_FILTER_CONTROLS';
export const SET_TASK_LIST_FILTER_BAR_VISIBLE = 'SET_TASK_LIST_FILTER_BAR_VISIBLE';
export const RESET_TASK_LIST_FILTER_CONTROL = 'RESET_TASK_LIST_FILTER_CONTROL';
export const RESET_ALL_TASK_LIST_FILTER_CONTROLS = 'RESET_ALL_TASK_LIST_FILTER_CONTROLS';

// charts filters
export const SET_CHART_FILTER_CONTROLS = 'SET_CHART_FILTER_CONTROLS';
export const SET_CHART_FILTER_CONTROL = 'SET_CHART_FILTER_CONTROL';

// tabs
export const SET_TAB = 'SET_TAB';

// sort order
export const SET_SORT_ORDER = 'SET_SORT_ORDER';

// users
export const SET_USERS = 'SET_USERS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

// skills
export const SET_SKILLS = 'SET_SKILLS';

// dateRange
export const SET_DATE_RANGE = 'SET_DATE_RANGE';

// db
export const SET_DB_STATUS = 'SET_DB_STATUS';
